"""CLI application for docxfix using Typer."""

from typing import Annotated

import typer

from docxfix.generator import DocumentGenerator
from docxfix.spec import DocumentSpec
from docxfix.validator import ValidationError, validate_docx

app = typer.Typer(
    name="docxfix",
    help=(
        "A CLI utility for creating docx fixtures with "
        "desirable characteristics for testing."
    ),
)


@app.command()
def create(
    output: Annotated[
        str,
        typer.Argument(help="Output path for the generated docx fixture"),
    ],
    template: Annotated[
        str | None,
        typer.Option(
            "--template",
            "-t",
            help="Template docx file to use as base",
        ),
    ] = None,
    validate: Annotated[
        bool,
        typer.Option(
            "--validate/--no-validate",
            help="Validate the generated document",
        ),
    ] = True,
    verbose: Annotated[
        bool,
        typer.Option(
            "--verbose",
            "-v",
            help="Enable verbose output",
        ),
    ] = False,
) -> None:
    """Create a new docx fixture."""
    if verbose:
        typer.echo(f"Creating docx fixture at: {output}")
        if template:
            typer.echo(f"Using template: {template}")

    try:
        # Create a simple document spec (basic example)
        spec = DocumentSpec(
            title="Test Document",
            author="Test User",
        )
        spec.add_paragraph("This is a test document generated by docxfix.")

        # Generate the document
        generator = DocumentGenerator(spec)
        generator.generate(output)

        if verbose:
            typer.echo("Document generated")

        # Validate if requested
        if validate:
            if verbose:
                typer.echo("Validating document...")
            validate_docx(output)
            if verbose:
                typer.echo("Validation passed")

        typer.echo("✓ Docx fixture created successfully!")

    except ValidationError as e:
        typer.echo(f"✗ Validation error: {e}", err=True)
        raise typer.Exit(code=1) from e
    except Exception as e:
        typer.echo(f"✗ Error creating fixture: {e}", err=True)
        raise typer.Exit(code=1) from e


@app.command()
def info() -> None:
    """Display information about docxfix."""
    from docxfix import __version__

    typer.echo(f"docxfix version {__version__}")
    typer.echo(
        "A CLI utility for creating docx fixtures with "
        "desirable characteristics for testing."
    )


def main() -> None:
    """Entry point for the CLI application."""
    app()


if __name__ == "__main__":
    main()
